services:
  - type: web
    name: martinos-dev-portfolio
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn --config gunicorn_config.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production